import { useMemo, useState } from 'react';
import { FiArrowLeft, FiArrowRight, FiBox, FiCheck, FiChevronRight, FiClipboard, FiCreditCard, FiGrid, FiHeart, FiHome, FiLock, FiMapPin, FiMenu, FiMinus, FiPackage, FiPlus, FiSearch, FiSettings, FiShoppingBag, FiSliders, FiStar, FiTrash2, FiTruck, FiUser, FiUsers, FiX } from 'react-icons/fi';
import './StoreApp.css';

const catalog=[
{id:1,name:'NovaTune Pro Wireless Headphones',category:'Electronics',brand:'NexAudio',price:2499,old:3999,rating:4.8,reviews:248,stock:18,image:'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=700&q=80'},
{id:2,name:'Pulse Active Smartwatch',category:'Wearables',brand:'Pulse',price:3299,old:5499,rating:4.7,reviews:184,stock:12,image:'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=700&q=80'},
{id:3,name:'Aura Glow Table Lamp',category:'Home & Living',brand:'Aura',price:1199,old:1999,rating:4.6,reviews:99,stock:25,image:'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=700&q=80'},
{id:4,name:'CloudStep Everyday Sneakers',category:'Fashion',brand:'CloudStep',price:1899,old:2999,rating:4.9,reviews:312,stock:8,image:'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=700&q=80'},
{id:5,name:'PixelFrame Mini Camera',category:'Electronics',brand:'PixelFrame',price:4599,old:6999,rating:4.7,reviews:142,stock:14,image:'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=700&q=80'},
{id:6,name:'Solis Ceramic Serve Set',category:'Home & Living',brand:'Solis',price:1499,old:2399,rating:4.5,reviews:76,stock:21,image:'https://images.unsplash.com/photo-1603199506016-b9a594b593c0?auto=format&fit=crop&w=700&q=80'},
{id:7,name:'Lumière Daily Skin Set',category:'Beauty',brand:'Lumière',price:899,old:1299,rating:4.6,reviews:201,stock:30,image:'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&w=700&q=80'},
{id:8,name:'Orbit Compact Speaker',category:'Electronics',brand:'Orbit',price:1799,old:2799,rating:4.8,reviews:164,stock:9,image:'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=700&q=80'}];
// A broad assortment makes the catalogue feel like a real marketplace rather than a demo shelf.
catalog.push(
{id:9,name:'BrewMate Pour Over Coffee Set',category:'Kitchen',brand:'BrewMate',price:1349,old:1999,rating:4.7,reviews:88,stock:18,image:'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=700&q=80'},
{id:10,name:'MotionFlex Yoga Mat',category:'Sports',brand:'MotionFlex',price:1099,old:1699,rating:4.8,reviews:266,stock:35,image:'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?auto=format&fit=crop&w=700&q=80'},
{id:11,name:'Terra Everyday Backpack',category:'Fashion',brand:'Terra',price:1599,old:2499,rating:4.6,reviews:151,stock:20,image:'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=700&q=80'},
{id:12,name:'FreshField Organic Snack Box',category:'Grocery',brand:'FreshField',price:699,old:899,rating:4.5,reviews:122,stock:42,image:'https://images.unsplash.com/photo-1599599810694-b5b37304c041?auto=format&fit=crop&w=700&q=80'},
{id:13,name:'Arc Mechanical Keyboard',category:'Electronics',brand:'Arc',price:2899,old:4299,rating:4.8,reviews:197,stock:11,image:'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=700&q=80'},
{id:14,name:'Haven Cotton Throw',category:'Home & Living',brand:'Haven',price:1299,old:1899,rating:4.7,reviews:104,stock:27,image:'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&w=700&q=80'},
{id:15,name:'GlowDrop Vitamin C Serum',category:'Beauty',brand:'GlowDrop',price:749,old:1099,rating:4.6,reviews:234,stock:32,image:'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=700&q=80'},
{id:16,name:'PlayGrid Strategy Board Game',category:'Gaming',brand:'PlayGrid',price:999,old:1499,rating:4.7,reviews:91,stock:16,image:'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?auto=format&fit=crop&w=700&q=80'}
);
const money=n=>`₹${Number(n).toLocaleString('en-IN')}`;
const api=async(path,options={})=>{const res=await fetch(`http://localhost:5000${path}`,{headers:{'Content-Type':'application/json',...(options.token?{Authorization:`Bearer ${options.token}`}:{})},...options,body:options.body?JSON.stringify(options.body):undefined});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.message||'Request failed');return data};

export default function StoreApp(){
 const [page,setPage]=useState('home'),[query,setQuery]=useState(''),[category,setCategory]=useState('All'),[cart,setCart]=useState([]),[wish,setWish]=useState([]),[user,setUser]=useState(null),[orders,setOrders]=useState([]),[selected,setSelected]=useState(null),[auth,setAuth]=useState(null),[toast,setToast]=useState(''),[menu,setMenu]=useState(false),[checkout,setCheckout]=useState(1),[coupon,setCoupon]=useState('');
 const notify=t=>{setToast(t);setTimeout(()=>setToast(''),2500)}; const filtered=useMemo(()=>catalog.filter(p=>(category==='All'||p.category===category)&&`${p.name} ${p.brand}`.toLowerCase().includes(query.toLowerCase())),[query,category]); const count=cart.reduce((s,x)=>s+x.qty,0),subtotal=cart.reduce((s,x)=>s+x.price*x.qty,0),discount=coupon==='NEX10'?Math.round(subtotal*.1):0,shipping=subtotal>999||subtotal===0?0:99,total=subtotal-discount+shipping;
 const navigate=p=>{setPage(p);setMenu(false);window.scrollTo({top:0,behavior:'smooth'})}; const add=p=>{setCart(c=>{const found=c.find(x=>x.id===p.id);return found?c.map(x=>x.id===p.id?{...x,qty:x.qty+1}:x):[...c,{...p,qty:1}]});notify('Added to your bag')}; const qty=(id,delta)=>setCart(c=>c.flatMap(x=>x.id===id?(x.qty+delta>0?[{...x,qty:x.qty+delta}]:[]):[x])); const save=p=>{setWish(w=>w.some(x=>x.id===p.id)?w.filter(x=>x.id!==p.id):[...w,p]);notify(wish.some(x=>x.id===p.id)?'Removed from wishlist':'Saved to wishlist')};
 const login=async(form,register)=>{try{const data=await api(`/api/auth/${register?'register':'login'}`,{method:'POST',body:form});setUser({...data.user,token:data.token});setAuth(null);notify(`Welcome${register?' to NexCart':''}, ${data.user.name.split(' ')[0]}!`)}catch(e){if(register){setUser({name:form.name,email:form.email,role:'customer'});setAuth(null);notify('Account created in demo mode')}else notify(e.message)}};
 const placeOrder=()=>{if(!user){setAuth('login');return}if(!cart.length)return;const order={id:`NC${1000+orders.length+1}`,items:cart,total,status:'Confirmed',date:new Date().toLocaleDateString('en-IN'),payment:checkout===3?'Online payment':'Cash on delivery'};setOrders([order,...orders]);setCart([]);setCheckout(4);notify('Your order is confirmed!')};
 return <div className="store"><div className="promo">Free delivery on orders over ₹999 <span>•</span> Use <b>NEX10</b> for 10% off</div><header><button className="hamburger" onClick={()=>setMenu(!menu)}><FiMenu/></button><button className="logo" onClick={()=>navigate('home')}><b>Nex</b>Cart<span>.</span></button><nav className={menu?'open':''}><button onClick={()=>navigate('home')}>Home</button><button onClick={()=>navigate('products')}>Shop</button><button onClick={()=>navigate('orders')}>Orders</button><button onClick={()=>navigate('admin')}>Admin</button></nav><label className="global-search"><FiSearch/><input value={query} onChange={e=>{setQuery(e.target.value);if(page!=='products')navigate('products')}} placeholder="Search products, brands and more"/></label><div className="head-actions"><button onClick={()=>user?navigate('profile'):setAuth('login')}><FiUser/><span>{user?'Profile':'Sign in'}</span></button><button onClick={()=>navigate('wishlist')}><FiHeart/>{wish.length>0&&<i>{wish.length}</i>}</button><button onClick={()=>navigate('cart')}><FiShoppingBag/>{count>0&&<i>{count}</i>}</button></div></header>
 <main>{page==='home'&&<Home go={navigate} add={add}/>} {page==='products'&&<Products list={filtered} category={category} setCategory={setCategory} add={add} save={save} wish={wish} select={p=>{setSelected(p);navigate('details')}}/>} {page==='details'&&selected&&<ProductDetails p={selected} add={add} save={save} saved={wish.some(x=>x.id===selected.id)} go={navigate}/>} {page==='wishlist'&&<Wishlist list={wish} add={add} remove={save} go={navigate}/>} {page==='cart'&&<Cart items={cart} qty={qty} total={total} subtotal={subtotal} coupon={coupon} setCoupon={setCoupon} discount={discount} shipping={shipping} go={navigate}/>} {page==='checkout'&&<Checkout step={checkout} setStep={setCheckout} user={user} total={total} place={placeOrder} go={navigate}/>} {page==='orders'&&<Orders orders={orders} go={navigate}/>} {page==='profile'&&<Profile user={user} orders={orders} logout={()=>{setUser(null);navigate('home');notify('Signed out')}} go={navigate}/>} {page==='admin'&&<Admin products={catalog} orders={orders} user={user} setAuth={setAuth}/>}</main>
 <footer><div><button className="logo"><b>Nex</b>Cart<span>.</span></button><p>Smart shopping, simplified.</p></div><div><b>Shop</b><button onClick={()=>navigate('products')}>All products</button><button onClick={()=>navigate('wishlist')}>Wishlist</button><button onClick={()=>navigate('orders')}>My orders</button></div><div><b>Customer care</b><a href="mailto:hello@nexcart.dev">Contact us</a><a href="#faq">Shipping & returns</a><a href="#faq">Help centre</a></div><div><b>Secure shopping</b><p><FiLock/> Protected checkout</p><p><FiTruck/> Fast delivery across India</p></div><small>© 2026 NexCart. All rights reserved.</small></footer>{selected&&<QuickView p={selected} close={()=>setSelected(null)} add={()=>{add(selected);setSelected(null)}}/>}{auth&&<Auth mode={auth} close={()=>setAuth(null)} submit={login} toggle={()=>setAuth(auth==='login'?'register':'login')}/>} {toast&&<div className="notice"><FiCheck/>{toast}</div>}</div>
}
function Home({go,add}){return <><section className="hero2"><div><p>NEW SEASON, NEW FAVOURITES</p><h1>Shop smarter.<br/><i>Live better.</i></h1><h2>Everything worth adding to your day, curated in one thoughtful place.</h2><button className="cta" onClick={()=>go('products')}>Start shopping <FiArrowRight/></button><button className="plain" onClick={()=>go('products')}>Explore categories</button></div><div className="hero-product"><div className="orb"/><img src={catalog[1].image} alt="Pulse smartwatch"/><article><small>FEATURED PICK</small><b>Pulse Active Watch</b><span>₹3,299 <FiArrowRight/></span></article></div></section><section className="trust"><span><FiTruck/><b>Free shipping</b> over ₹999</span><span><FiBox/><b>Easy returns</b> within 14 days</span><span><FiLock/><b>Secure payment</b> every time</span><span><FiStar/><b>4.8/5 rating</b> by shoppers</span></section><section className="homepage-section"><div className="title"><div><small>EXPLORE NEXCART</small><h2>Made for every mood.</h2></div><button onClick={()=>go('products')}>View everything <FiArrowRight/></button></div><div className="category-cards">{[['Electronics','https://images.unsplash.com/photo-1498049794561-7780e7231661?auto=format&fit=crop&w=500&q=80'],['Fashion','https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=500&q=80'],['Home & Living','https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=500&q=80'],['Beauty','https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=500&q=80']].map(([n,img])=><button key={n} onClick={()=>go('products')}><img src={img} alt=""/><b>{n}</b><FiArrowRight/></button>)}</div></section><section className="homepage-section picks"><div className="title"><div><small>POPULAR RIGHT NOW</small><h2>Good picks, no guesswork.</h2></div><button onClick={()=>go('products')}>Shop best sellers <FiArrowRight/></button></div><div className="mini-grid">{catalog.slice(0,4).map(p=><MiniCard p={p} add={add} key={p.id}/>)}</div></section></>}
function Products({list,category,setCategory,add,save,wish,select}){const cats=['All','Electronics','Wearables','Fashion','Home & Living','Beauty','Kitchen','Sports','Grocery','Gaming'];return <section className="catalog-page"><div className="crumb">Home <FiChevronRight/> Shop</div><div className="catalog-heading"><div><h1>Find your next favourite.</h1><p>{list.length} carefully selected products</p></div><button className="filter"><FiSliders/> Filters</button></div><div className="shop-layout"><aside><b>Categories</b>{cats.map(c=><button className={c===category?'chosen':''} onClick={()=>setCategory(c)} key={c}>{c}</button>)}<hr/><b>Price range</b><label><input type="checkbox"/> Under ₹1,000</label><label><input type="checkbox"/> ₹1,000 - ₹3,000</label><label><input type="checkbox"/> Above ₹3,000</label><hr/><b>Customer rating</b><label><input type="checkbox"/> 4★ & above</label><label><input type="checkbox"/> 3★ & above</label></aside><div className="product-list">{list.map(p=><ProductCard p={p} add={add} save={save} saved={wish.some(x=>x.id===p.id)} select={select} key={p.id}/>)}</div></div></section>}
function ProductCard({p,add,save,saved,select}){return <article className="pcard"><div><span>{Math.round((1-p.price/p.old)*100)}% off</span><button onClick={()=>save(p)} className={saved?'saved':''}><FiHeart/></button><img src={p.image} alt={p.name} onClick={()=>select(p)}/></div><small>{p.category} · {p.brand}</small><h3 onClick={()=>select(p)}>{p.name}</h3><p className="stars"><FiStar/> {p.rating} <em>({p.reviews})</em></p><p className="product-price"><b>{money(p.price)}</b> <s>{money(p.old)}</s></p><button className="to-bag" onClick={()=>add(p)}><FiPlus/> Add to bag</button></article>}
function MiniCard({p,add}){return <ProductCard p={p} add={add} save={()=>{}} saved={false} select={()=>{}}/>}
function Wishlist({list,add,remove,go}){return <section className="simple-page"><div className="crumb">Home <FiChevronRight/> Wishlist</div><h1>Saved for later <span>({list.length})</span></h1>{list.length?<div className="product-list wish-list">{list.map(p=><ProductCard p={p} add={add} save={remove} saved select={()=>{}} key={p.id}/>)}</div>:<Empty icon={<FiHeart/>} title="Your wishlist is waiting." text="Save products you want to come back to." action="Discover products" onClick={()=>go('products')}/>}</section>}
function Cart({items,qty,total,subtotal,coupon,setCoupon,discount,shipping,go}){return <section className="cart-page"><div><div className="crumb">Home <FiChevronRight/> Shopping bag</div><h1>Your shopping bag <span>({items.reduce((s,x)=>s+x.qty,0)} items)</span></h1>{items.length?<div className="bag-items">{items.map(x=><article key={x.id}><img src={x.image} alt=""/><div><small>{x.category}</small><h3>{x.name}</h3><b>{money(x.price)}</b><div className="stepper"><button onClick={()=>qty(x.id,-1)}><FiMinus/></button><span>{x.qty}</span><button onClick={()=>qty(x.id,1)}><FiPlus/></button></div></div><button className="delete" onClick={()=>qty(x.id,-x.qty)}><FiTrash2/></button></article>)}</div>:<Empty icon={<FiShoppingBag/>} title="Your bag is empty." text="Let’s find something you’ll love." action="Start shopping" onClick={()=>go('products')}/>}</div>{items.length>0&&<aside className="summary-card"><h3>Order summary</h3><div className="coupon"><input value={coupon} onChange={e=>setCoupon(e.target.value.toUpperCase())} placeholder="Coupon code"/><button>Apply</button></div>{coupon==='NEX10'&&<p className="success">Coupon applied — 10% off!</p>}<p><span>Subtotal</span><b>{money(subtotal)}</b></p><p><span>Shipping</span><b>{shipping?money(shipping):'FREE'}</b></p>{discount>0&&<p><span>Discount</span><b className="success">−{money(discount)}</b></p>}<hr/><p className="grand"><span>Total</span><b>{money(total)}</b></p><button className="cta full" onClick={()=>go('checkout')}>Proceed to checkout <FiArrowRight/></button><small><FiLock/> Secure checkout</small></aside>}</section>}
function Checkout({step,setStep,user,total,place,go}){if(!user)return <section className="simple-page"><Empty icon={<FiLock/>} title="Sign in to check out." text="Your bag will be saved while you sign in." action="Sign in" onClick={()=>go('profile')}/></section>;if(step===4)return <section className="complete"><div><FiCheck/><p>ORDER CONFIRMED</p><h1>Thank you, {user.name.split(' ')[0]}!</h1><h2>Your order is being prepared. We’ll notify you when it ships.</h2><b>Order total: {money(total)}</b><button className="cta" onClick={()=>go('orders')}>Track your order <FiArrowRight/></button></div></section>;return <section className="checkout"><div><div className="crumb">Cart <FiChevronRight/> Checkout</div><h1>Checkout</h1><div className="checkout-steps"><span className={step>=1?'on':''}>1. Address</span><span className={step>=2?'on':''}>2. Delivery</span><span className={step>=3?'on':''}>3. Payment</span></div>{step===1&&<div className="form-card"><h2>Delivery address</h2><div className="field-row"><label>First name<input defaultValue={user.name.split(' ')[0]}/></label><label>Last name<input defaultValue={user.name.split(' ').slice(1).join(' ')}/></label></div><label>Street address<input placeholder="House number, street, area"/></label><div className="field-row"><label>City<input placeholder="City"/></label><label>PIN code<input placeholder="000000"/></label></div><label>Phone number<input placeholder="+91"/></label><button className="cta" onClick={()=>setStep(2)}>Continue <FiArrowRight/></button></div>}{step===2&&<div className="form-card"><h2>Delivery option</h2><label className="radio"><input type="radio" defaultChecked name="delivery"/><span><b>Standard delivery</b><small>3–5 business days · Free</small></span></label><label className="radio"><input type="radio" name="delivery"/><span><b>Express delivery</b><small>1–2 business days · ₹149</small></span></label><button className="cta" onClick={()=>setStep(3)}>Continue to payment <FiArrowRight/></button></div>}{step===3&&<div className="form-card"><h2>Payment method</h2><label className="radio"><input type="radio" defaultChecked name="pay"/><span><b>Cash on delivery</b><small>Pay when your order arrives</small></span></label><label className="radio"><input type="radio" name="pay"/><span><b>Mock online payment</b><small>UPI, card or net banking</small></span></label><button className="cta" onClick={place}>Place secure order <FiLock/></button></div>}</div><aside className="summary-card"><h3>Total payable</h3><p className="grand"><b>{money(total)}</b></p><small><FiLock/> Payment information is secure</small></aside></section>}
function ProductDetails({p,add,save,saved,go}){const [tab,setTab]=useState('Description');return <section className="details"><div className="crumb"><button onClick={()=>go('products')}><FiArrowLeft/> Back to shop</button><FiChevronRight/>{p.category}<FiChevronRight/>{p.name}</div><div className="details-main"><div className="details-image"><span>BESTSELLER</span><img src={p.image} alt={p.name}/></div><div className="details-copy"><p className="eyeline">{p.category.toUpperCase()} · {p.brand.toUpperCase()}</p><h1>{p.name}</h1><p className="stars"><FiStar/> {p.rating} <em>{p.reviews} verified customer reviews</em></p><div className="detail-price"><b>{money(p.price)}</b><s>{money(p.old)}</s><span>{Math.round((1-p.price/p.old)*100)}% off</span></div><p className="detail-description">A carefully selected everyday essential made to feel considered, useful and genuinely good to own. Premium quality, delivered with the NexCart promise.</p><div className="stock"><FiCheck/> In stock — ships in 24 hours</div><div className="detail-actions"><button className="cta" onClick={()=>{add(p);go('cart')}}><FiShoppingBag/> Add to bag</button><button className={saved?'detail-save saved':'detail-save'} onClick={()=>save(p)}><FiHeart/> {saved?'Saved':'Save for later'}</button></div><div className="detail-perks"><span><FiTruck/> Free delivery over ₹999</span><span><FiBox/> 14-day easy returns</span><span><FiLock/> Secure payments</span></div></div></div><div className="detail-tabs"><div>{['Description','Specifications','Reviews'].map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div>{tab==='Description'&&<p>Designed to make the everyday easier. This product combines thoughtful design with dependable performance, and is inspected before it reaches your door.</p>}{tab==='Specifications'&&<div className="spec-grid"><span>Brand <b>{p.brand}</b></span><span>Category <b>{p.category}</b></span><span>SKU <b>NC-{String(p.id).padStart(4,'0')}</b></span><span>Availability <b>{p.stock} units in stock</b></span></div>}{tab==='Reviews'&&<div className="review"><FiStar/> <b>{p.rating} out of 5</b><p>“Great quality, arrived quickly and exactly as described.”</p><small>Verified NexCart customer</small></div>}</div></section>}
function Orders({orders,go}){return <section className="simple-page"><div className="crumb">Home <FiChevronRight/> Orders</div><h1>Your orders</h1>{orders.length?orders.map(o=><article className="order" key={o.id}><div><b>Order {o.id}</b><small>Placed on {o.date}</small></div><span className="status"><FiCheck/> {o.status}</span><b>{money(o.total)}</b><button onClick={()=>go('products')}>Buy again <FiArrowRight/></button></article>):<Empty icon={<FiPackage/>} title="No orders yet." text="When you place an order, it will appear here." action="Shop now" onClick={()=>go('products')}/>}</section>}
function Profile({user,orders,logout,go}){if(!user)return <section className="simple-page"><Empty icon={<FiUser/>} title="Welcome to NexCart." text="Sign in to manage orders, addresses and your profile." action="Sign in" onClick={()=>go('home')}/></section>;return <section className="profile"><aside><div className="avatar">{user.name[0]}</div><h2>{user.name}</h2><p>{user.email}</p><button><FiUser/> Personal details</button><button onClick={()=>go('orders')}><FiPackage/> Your orders <span>{orders.length}</span></button><button><FiMapPin/> Saved addresses</button><button><FiSettings/> Settings</button><button className="signout" onClick={logout}>Sign out</button></aside><div><p className="eyeline">ACCOUNT OVERVIEW</p><h1>Good to see you, {user.name.split(' ')[0]}.</h1><div className="account-cards"><article><FiPackage/><b>{orders.length}</b><span>Orders placed</span></article><article><FiHeart/><b>Saved</b><span>Wishlist items</span></article><article><FiMapPin/><b>1</b><span>Saved address</span></article></div><h2>Quick actions</h2><div className="quick-actions"><button onClick={()=>go('orders')}><FiClipboard/> Track an order <FiArrowRight/></button><button onClick={()=>go('products')}><FiShoppingBag/> Continue shopping <FiArrowRight/></button></div></div></section>}
function Admin({products,orders,user,setAuth}){if(!user||user.role!=='admin')return <section className="simple-page"><Empty icon={<FiLock/>} title="Admin workspace" text="Sign in with the demo admin account to access the dashboard." action="Admin sign in" onClick={()=>setAuth('login')}/><p className="demo">Demo: admin@nexcart.dev · Admin@123</p></section>;return <section className="admin"><aside><b><FiGrid/> NexCart Admin</b><button className="active"><FiHome/> Dashboard</button><button><FiBox/> Products</button><button><FiClipboard/> Orders</button><button><FiUsers/> Customers</button><button><FiSettings/> Settings</button></aside><div><p className="eyeline">OVERVIEW</p><h1>Store dashboard</h1><div className="metrics"><Metric icon={<FiCreditCard/>} label="Revenue" value={money(orders.reduce((s,o)=>s+o.total,0))}/><Metric icon={<FiPackage/>} label="Orders" value={orders.length}/><Metric icon={<FiUsers/>} label="Customers" value="1,248"/><Metric icon={<FiBox/>} label="Products" value={products.length}/></div><div className="admin-panels"><article><h2>Inventory alerts</h2>{products.filter(p=>p.stock<15).map(p=><p key={p.id}><span>{p.name}</span><b>{p.stock} left</b></p>)}</article><article><h2>Recent orders</h2>{orders.length?orders.map(o=><p key={o.id}><span>{o.id}</span><b>{o.status}</b></p>):<p className="muted">Orders will appear here after checkout.</p>}</article></div></div></section>}
function Metric({icon,label,value}){return <article>{icon}<span>{label}</span><b>{value}</b></article>}
function QuickView({p,close,add}){return <div className="modal-bg" onMouseDown={close}><article className="quick" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={close}><FiX/></button><img src={p.image} alt={p.name}/><div><small>{p.category} · {p.brand}</small><h1>{p.name}</h1><p className="stars"><FiStar/> {p.rating} <em>{p.reviews} verified reviews</em></p><h2>{money(p.price)} <s>{money(p.old)}</s></h2><p>Thoughtfully designed for everyday use, with the quality and comfort you expect from NexCart picks.</p><ul><li>In stock — ready to ship</li><li>Free delivery over ₹999</li><li>14-day easy returns</li></ul><button className="cta full" onClick={add}><FiShoppingBag/> Add to bag</button></div></article></div>}
function Auth({mode,close,submit,toggle}){const [name,setName]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState('');const register=mode==='register';return <div className="modal-bg"><form className="auth" onSubmit={e=>{e.preventDefault();submit({name,email,password},register)}}><button type="button" className="close" onClick={close}><FiX/></button><p className="eyeline">{register?'CREATE ACCOUNT':'WELCOME BACK'}</p><h1>{register?'Join NexCart.':'Sign in to NexCart.'}</h1><p>{register?'Save favourites, track orders and shop faster.':'Your good finds are waiting.'}</p>{register&&<label>Full name<input required value={name} onChange={e=>setName(e.target.value)} placeholder="Your name"/></label>}<label>Email address<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label><label>Password<input required type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="••••••••"/></label><button className="cta full">{register?'Create account':'Sign in'} <FiArrowRight/></button><button type="button" className="switch" onClick={toggle}>{register?'Already have an account? Sign in':'New here? Create an account'}</button></form></div>}
function Empty({icon,title,text,action,onClick}){return <div className="empty-state"><div>{icon}</div><h2>{title}</h2><p>{text}</p><button className="cta" onClick={onClick}>{action} <FiArrowRight/></button></div>}
